spring:
  security:
    oauth2:
      client:
        registration:
          user-service:
            client-id: user-service
            authorization-grant-type: password
            scope: openid
            provider: keycloak
          sign-service:
            client-id: sign-service
            authorization-grant-type: password
            scope: openid
            provider: keycloak


        provider:
          keycloak:
            token-uri: http://127.0.0.1:8090/realms/blooddonor_app/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  metrics:
#    export:
#      prometheus:
#        enabled: true