spring:
  security:
    oauth2:
      client:
        registration:
          user-service:
            client-id: user-service
            authorization-grant-type: password
            scope: openid
            provider: keycloak
          sign-service:
            client-id: sign-service
            authorization-grant-type: password
            scope: openid
            provider: keycloak


        provider:
          keycloak:
            token-uri: http://127.0.0.1:8090/realms/blooddonor_app/protocol/openid-connect/token

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        service-name: patient-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
